# Start from the official Analyzer image
FROM ghcr.io/thehive-project/opencti_searchexactobservable:2

# Force upgrade the library to match your OpenCTI version
RUN pip install --upgrade pycti==6.9.10
