## Secret key
# Play uses a secret key for a number of things, including signing session cookies.
# This key should be kept secret.
play.http.secret.key="loremipsumdolorsitametconsecteturadipiscingelit"

## Elasticsearch
search {
  index = "cortex"
  uri = "http://cortex-elasticsearch:9200"
}

## Analyzers and Responders
# Initial activation of analyzers and responders
analyzer {
  urls = [
    "/opt/cortex/analyzers/analyzers"
  ]
}

responder {
  urls = [
    "/opt/cortex/analyzers/responders"
  ]
}

job {
  runner = ["docker"]
}
